---
title: "Enough R to write a thesis"
description: Enough R to write a thesis
author: "Biostats team"
site: bookdown::bookdown_site
documentclass: book
date: "`r Sys.Date()`"
github-repo: biostats-r/biostats
output:
  bookdown::bs4_book:
    css: "css/style-chapters.css"
---

# Enough R to write a thesis {-}

The  biostats `r fontawesome::fa(name = "r-project", fill = "steelblue")` books, apps, and tutorials are written to give you enough `r fontawesome::fa(name = "r-project", fill = "steelblue")` skills to write a thesis.

The books emphasis reproducible research.


## Biostats books {-}

### Working in R {-}
Learn how to import, manipulate and visualise data with our [working in R](workingInR/index.html) book. 
After an introduction to R, this book has a tidyverse flavour, showing how to manipulate data with `dplyr` and make publishable plots with `ggplot2`.
It includes lots of exercises to hone your skills.

### Statistics in R {-}

Coming soon!

### R markdown {-}

Learn how to write reproducible documents (anything from a course assignment to a thesis or manuscript) in [R markdown](rmarkdown/index.html). 
All the biostats books were written in R markdown; you can see the source code in our [repo](https://github.com/biostats-r/biostats) on GitHub.

### Git and GitHub {-}

Learn how to use version control with our step-by-step guide to setting up and using [git and GitHub](github/index.html) in RStudio.

### Writing an R package {-}

Want to make your code into an R package?
Our guide to [writing an R package](package/index.html) will show you how.

## Biostats apps and tutorials {-}

The [biostats apps and `learnr` tutorials](https://github.com/biostats-r/biostats.tutorials) can be installed with 

```{r eval = FALSE}
# install remotes if you don't have it already
# install.packages("remotes")

remotes::install_github("biostats-r/biostats.tutorials")
```

## The Biostats team {-}

These books are a collaboration between the [Department of Biological Sciences](https://www.uib.no/en/bio), [University of Bergen](https://www.uib.no/en) and the [Department of Mathematical Sciences](https://www.ntnu.edu/imf), [University of Trondheim](https://www.ntnu.edu/).

- Dr Aud Halbritter
- Dr Josh Lynn
- Dr Emily G. Simmonds
- Dr Jonathan Soule
- Dr Richard J. Telford

This is [BioCeed](https://bioceed.w.uib.no/) product.