---
title: "Importing data in R"
output:
  bookdown::html_document2:
  highlight: tango
toc: true
toc_float: true
css: ../css/style-chapters.css
---
  
``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library("tidyverse")

data(penguins, package = "palmerpenguins")

source("../Templates/biostats_theme.R")
theme_set(theme_biostats)
```

### Before we start {- .facta .toc-ignore}

You must be familiar with objects and data types, with using functions and arguments.

# Foreword

In this chapter, you will learn to import data from file into an R object. The R base package and several packages come with a set of functions that can do the job. Here, we will focus on the functions which are part of the package `tidyverse`. So, if it is not done yet, install the package with `install.packages("tidyverse")` and/or load it with `library(tidyverse)`.

# Five functions to import data from a file

Here, you will learn about 5 functions: `read_csv()`, `read_csv2()`, `read_excel()`, `read_table()` and `read_fwd()`. All these functions have the same purpose, namely to:

1. read a file,
2. retrieve the data, 
3. place the data properly into a data frame.

The main difference is that each of these functions is dedicated to reading one specific type of file.

## read_delim

; , or space



## read_csv()

In a _*C*omma *S*eparated *V*alues_ file, the data is delimited by a comma `,` (hence the name). It is possibly the most common type 

## read_csv2()
In countries (such as most of the European countries) where a comma is used as a decimal separator, the data is delimited by a semi-colon `;`. 


other types csv, fwf

## read_excel()






# Working with read_csv()

# Working with read_excel()


# Check for errors before going further

### What's next {- .facta .toc-ignore}





