---
output:
  html_document:
    css: custom-blockquote.css
---

```{r setup&variables, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# title: Which ANOVA – One-way? Two-way? Repeated measures?
# author: jonathan
# revised: 15/4/2020 

WEB <- c("https://bioceed.uib.no/dropfolder/bioSTATS/Rmd/Basic/ANOVA/whichANOVA.html")
GIT <- c("https://github.com/jonathansoule/biostats/blob/master/Basic/ANOVA/whichANOVA.Rmd")

```

The **different types of ANOVA** are there to help you find out whether the means of 2 or more samples are different from each other. This being said, the ANOVA tests *per se* will not tell you which of the tested groups is/are different from others. ANOVA will tell you whether a factor has a significant effect on the response variable. 

To get to know which groups are significantly different, you will need a second test, a [*post hoc* test](http://biostats.w.uib.no/post-hoc-tests/){target="_blank"} to make pairwise comparisons between groups. Note however that *post hoc* tests may be run *ONLY* if the ANOVA tells you that there actually is a main effect of a factor (or an interaction). If not, any result from *post hoc* tests must be discarded, even if there apparently exist significant differences between specific groups according to these tests.

<br/>

Here are the general assumptions for ANOVA:

+ the sample should be normally distributed (check it with the [Shapiro-Wilks](http://biostats.w.uib.no/test-for-normality-shapiro-wilks-test/){target="_blank"} test)
+ variances should be equal ([Fisher's F test](http://biostats.w.uib.no/1-comparing-two-variances/){target="_blank"} may only be used for 2 groups; alternatives are [Levene's test](http://biostats.w.uib.no/test-for-homogeneity-of-variances-levenes-test/){target="_blank"}, the [Fligner-Killeen test](http://biostats.w.uib.no/test-for-homogeneity-of-variances-levenes-test/){target="_blank"} of homogeneity of variances.)
+ predictor variables are categorical
+ [no outlier](http://biostats.w.uib.no/finding-outliers/){target="_blank"} must be found;

If one or more assumptions are violated, alternative tests may be used. 

<br/>

Now, **which ANOVA** do I run?

It all depends on how many factors you need to compare and on their nature. In brief:

+ Run a [**one-way ANOVA**](https://biostats.w.uib.no/one-way-anova/){target="_blank"} if your experimental design is based on one predictor variable (for example: drug treatment, species, location, etc) which includes at least two levels (for example: treatment A, treatment B, treatment C and control),
+ Run a [**factorial ANOVA**](https://biostats.w.uib.no/factorial-design/){target="_blank"} if your experimental design is based on two, three or more preditor variables (for example: drug treatment AND species, citizenship AND gender, species AND gender AND drug treatment, etc) and each variable has at least two levels,
+ Run a [**repeated measures ANOVA**](https://biostats.w.uib.no/repeated-measures-anova/){target="_blank"} if you have a single predictor variable and there is dependency in your data, meaning that subjects have been measured repeatedly, at different time points or in different conditions (for example: all individuals are tested at birth, during childhood and during adulthood, or all individuals have been submitted to and tested after three consecutive drug treatments).
+ Run a [**factorial repeated measures ANOVA**](https://biostats.w.uib.no/factorial-repeated-measures-anova-two-way-repeated-measures-anova/){target="_blank"} if you have at least two predictor variables and there is dependency in your data, meaning that subjects have been measured repeatedly, at different time points or in different conditions (for example: all individuals grouped by citizenship are tested at birth, during childhood and during adulthood, or all individuals grouped by gender have been submitted to and tested after three consecutive drug treatments).

<br/><br/>

***
<!-- UNCOMMENT TO ACTIVATE
Get the Rmarkdown file corresponding to this page on [GitHub](`r GIT`){target="_blank"}.
-->
