
# Collect data

``` {r setup, include=FALSE}

library(knitr)
library(lubridate)

```

## Paper or digital data entry

Should data be collected on paper or digitally.
There is no clear answer and it depends on what type of data you are collecting, and where.

Both are common and they have their advantages and disadvantages.
Here, we just want to mention that digital data collection can be useful, because it saves the step of digitizing, which is a source of errors.
Additionally, digital data entry allows to build in checks to avoid missing values.


## Content

What information should your spreadsheet contain?
This is not en exhaustive list, but gives guidance on what information it should contain:

- ID (unique ID for each observation, individual)
- Date, time, observation nr
- Location: region/site
- Experimental design: block/plot, nr of observation, treatments
- Organism: species/population/genet
- response variable(s)
- predictors
- recorder/scribe
- other observations: weather
- notes


