
# Formatting for a thesis or article

## Formatting for a thesis

We have made a quarto Masters thesis template that you can [download](https://github.com/biostats-r/quartothesis) and use. 
It takes care of formatting the thesis' cover page which otherwise would need you to know some LaTeX.

## Journal-specific formatting

Manuscript templates have been developed for some publisher's journals. 
To use a template, run this code in the RStudio **Terminal** (Not the console), changing the publisher name as necessary for one on this [list](https://github.com/quarto-journals/) of the available templates, and follow the instructions. 

``` bash
quarto use template quarto-journals/plos
```

This will download the journal template and make a qmd file with the YAML set up. 
Edit this file so it becomes your manuscript.
Render as usual to produce the PDF and the tex file that you might need for submission.
You can read more about journal formats in the [Quarto guide](https://quarto.org/docs/journals/).

## Line numbers

If you are creating a PDF, you can include line numbers by adding a header-includes section to the YAML.

``` yaml
---
title: "My Manuscript"
format: pdf
header-includes:
   - \usepackage{lineno}
   - \linenumbers
---
```


Other LaTeX packages can be added in a similar way to add extra functionality, for example, pages in [landscape](https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf).
