---
output: html_document
---

```{r setup&variables, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# title: comparing two means - which test
# author: jonathan
# revised: 10/1/2020 

WEB <- c("https://bioceed.uib.no/dropfolder/bioSTATS/Rmd/Basic/2-sample/2means-whichtest.html")
GIT <- c("https://github.com/jonathansoule/biostats/blob/master/Basic/2-sample/2means-whichtest.Rmd")

```

Very often, you will try to compare the means of two samples to define whether these samples are different from each other. Several tests can be used for that, depending on whether the samples are related to each other in any way. Let's see the different cases that you may encounter.
 
#### Case 1: the samples are independent (they have nothing to do with each other)
The samples are not related to each other. Their is no direct link between any of the measurements in your samples.

  **Case 1a**: the samples are normally distributed; you may use a parametric test. Go for [Student's t-test](http://biostats.w.uib.no/comparing-two-means-t-test/){target="_blank"}.

  **Case 1b**: the samples are not normally distributed; you have to choose a non-parametric test. Choose either [Mann-Whitney U test](http://biostats.w.uib.no/comparing-two-means-mann-whitney-u-test/){target="_blank"} or [Kruskal-Wallis test](http://biostats.w.uib.no/comparing-two-means-kruskal-wallis-test/){target="_blank"}.

#### Case 2: the samples are dependent (there exist a form of relationship between the two groups).
The samples are somehow related: they work by pairs. This means that one specific data in one of the samples is directly link to one of the data in the other sample. Examples of this are:

  + measurements of a variable BEFORE AND AFTER a specific event (application of a drug, removal of a factor)
  + measurements of a variable at two different time points in the sample's existence (youth vs. adulthood, morning vs. evening)
  + measurements of a variable at two different locations which may both be affected by a same phenomenon or external factor (weather data from to close locations, same city, ...)
  + measurements of a variable on pairs of individuals with common background

Note that one may talk of **repeated measurements** when pairs of data correspond to measurements taken at different time points during an experiment.

  **Case 2a**: the samples are normally distributed; you may use a parametric test. Go for [Student's paired t-test](http://biostats.w.uib.no/comparing-two-means-students-paired-t-test/){target="_blank"}.

  **Case 2b**: the samples are not normally distributed; you have to choose a non-parametric test. Choose [Wilcoxon signed-rank test](http://biostats.w.uib.no/comparing-two-means-wilcoxon-signed-rank-test/){target="_blank"}.
<br/><br/>

***
<!-- UNCOMMENT TO ACTIVATE
Get the Rmarkdown file corresponding to this page on [GitHub](`r GIT`){target="_blank"}.
-->
