---
engine: knitr
---

# Introduction

### Before we start {- .facta .toc-ignore}

You must have successfully switched on your PC, Mac or Linux machine. 

## What is `r fontawesome::fa(name = "r-project", fill = "steelblue")`?

`r fontawesome::fa(name = "r-project", fill = "steelblue")` is a powerful statistical and graphical tool which is available for most platforms (Windows, Mac, Linux, etc.). 
R is both free and open source, which means that anyone can freely use it and access its source code, understand what it actually does with your data, create add-ons to fit a specific purpose, etc.  

R is not a conventional software where all tools are available via a graphical user interface (GUI) with menus and buttons. 
Instead, users run commands via a script, and read the output either in a console, or in a separate, dedicated window.  

R is also a programming language organized around objects that store data and functions that manipulate data. 
Throughout this website, you will learn this language and the art of writing meaningful code chunks that transform raw data into understandable results in the form of figures, tables, and reports.

### Why use R?

R has been widely adopted by biologists and more generally by the life science community. The reasons include:

+ R is free.
+ R is efficient in terms of data processing, even with large data sets. 
+ R has a large, friendly online community ready to help and answer your questions.
+ R is adaptable: you will most certainly find one or several packages (i.e. add-ons) for your discipline, or for solving the problems you face.
+ R is transparent: the code behind functions and packages is accessible, meaning that you know exactly what R does to your raw data (you don't have to assume it).
+ R produces clean figures ready for publication in scientific journals.
+ R allows for reproducible research: anyone running your code on your data will get the exact same result as you do. 
+ R code is easy to share and publish. 
+ R contributes to replicability: anyone can use your published code on another data set to replicate your findings (or not).

::: {.column-margin}
### Contributors {.unlisted .unnumbered}

-   Jonathan Soulé
-   Richard Telford
:::
