```{r setup&variables, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# title: post-hoc tests
# author: jonathan
# revised: 15/4/2020

WEB <- c("https://bioceed.uib.no/dropfolder/bioSTATS/Rmd/Basic/post-hoc tests/post-hoc-tests.html")
GIT <- c("https://github.com/jonathansoule/biostats/blob/master/Basic/post-hoc tests/post-hoc-tests.Rmd")
```

*Post hoc* tests are commonly used as a follow up to an F-test (such as [one-way-ANOVA](https://biostats.w.uib.no/one-way-anova/){target="_blank"}, [factorial ANOVA](https://biostats.w.uib.no/factorial-design/){target="_blank"}, …). These tests may be performed **only if** the F-test shows that there exists a significant difference between the means of the tested groups, a main effect of a factor or an interaction. **If not**, *post hoc* tests are not be used!

There exist many different tests, more or less conservative and adpated to your design, and finding the right test to use is often a challenge as one may be tempted to use a less conservative test to find lower p-value, with the increased risk to get type I errors (incorrect rejection of the null hypothesis stating that there is no difference between means).

This section of bioSTATS is not intended to tell you which test or which function to choose in each situation; there are plenty of courses and online resources that do it already in a great way. Instead we show you the way to perform some of these common tests in R.

Here are a few useful functions in R that run *post hoc* tests. Let’s have a closer look at them:

+ [*post hoc* pairwise comparisons](https://biostats.w.uib.no/post-hoc-tests-pairwise-comparisons/){target="_blank"} with `pairwise.t.test()`,
+ [Tukey Honest Significant Difference](https://biostats.w.uib.no/post-hoc-tests-tukey-hsd/){target="_blank"} (Tukey HSD) with `TukeyHSD()`.
+ [multiple comparisons in linear models (one-way ANOVA)](https://biostats.w.uib.no/post-hoc-tests-multiple-comparisons-in-linear-models/){target="_blank"}
+ [multiple comparisons in linear mixed effect models (repeated measures ANOVA)](https://biostats.w.uib.no/post-hoc-tests-multiple-comparisons-in-linear-mixed-effect-models/){target="_blank"}
+ [multiple comparisons in linear models (factorial design - two-way ANOVA)](https://biostats.w.uib.no/post-hoc-tests-multiple-comparisons-in-linear-mixed-effect-models-2/){target="_blank"}
+ [multiple comparisons in linear mixed effect models (factorial design - two-way repeated measures ANOVA)](https://biostats.w.uib.no/post-hoc-tests-multiple-comparisons-in-linear-models-2/){target="_blank"}

<br/><br/>

***
<!-- UNCOMMENT TO ACTIVATE
Get the Rmarkdown file corresponding to this page on [GitHub](`r GIT`){target="_blank"}.
-->
