---
output:
  html_document:
    css: custom-blockquote.css
---

```{r setup&variables, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# title: Which ANOVA – One-way? Two-way? Repeated measures?
# author: jonathan
# revised: 16/1/2020 

WEB <- c("https://bioceed.uib.no/dropfolder/bioSTATS/Rmd/Basic/ANOVA/whichANOVA.html")
GIT <- c("https://github.com/jonathansoule/biostats/blob/master/Basic/ANOVA/whichANOVA.Rmd")

```

The **different types of ANOVA** are there to help you find out whether the means of 3 or more samples are different from each other. This being said, the ANOVA tests *per se* will not tell you which of the tested groups is/are different from others. ANOVA will tell you whether at least one of them is statistically different from the others!

To get to know which groups are significantly different, you will need a second test, a [*post hoc* test](http://biostats.w.uib.no/post-hoc-tests/){target="_blank"} to make pairwise comparisons between groups. Note however that *post hoc* tests may be run *only* if the ANOVA tells you that there actually is a difference between some groups. If not, any result from *post hoc* tests will be invalid.

 

Here are the general assumptions for ANOVA:

+ the sample should be normally distributed (check it with the [Shapiro-Wilks](http://biostats.w.uib.no/test-for-normality-shapiro-wilks-test/){target="_blank"} test)
+ variances should be equal ([Fisher's F test](http://biostats.w.uib.no/1-comparing-two-variances/){target="_blank"} may only be used for 2 groups; alternatives are [Levene's test](http://biostats.w.uib.no/test-for-homogeneity-of-variances-levenes-test/){target="_blank"}, the [Fligner-Killeen test](http://biostats.w.uib.no/test-for-homogeneity-of-variances-levenes-test/){target="_blank"} of homogeneity of variances.)
+ independent variables are categorical
+ note that outliers might be a problem in many circumstances

If one or more assumptions are violated, alternative tests exists. They will be discussed in the following sections.

 

Now, **which ANOVA** do I run?

It all depends on how many factors you need to compare and on their nature. In brief:

+ Run a **one-way ANOVA** if your experimental design is based on one variable (for example: drug treatment, species, location, etc) which includes at least three levels (for example: treatment A, treatment B, treatment C and control). Alternatively, run a **Welch F test** or a **Kruskal-Wallis H test** if assumptions like equality of variance or normality of distribution are violated.
+ Run a **two-way ANOVA** if your experimental design is based on two independent variables (for example: drug treatment AND species, citizenship AND gender, etc) and each variable has at least two levels.
+ Run a **three-way ANOVA** if your experimental design is based on three independent variables (for example: species, gender AND drug treatment.).
+ Run a **repeated-measures** ANOVA if the levels of (one of) your variable(s) correspond to measurements done at different time points or in different conditions and all individuals are tested at these consecutive time points or in these different conditions (for example: all individuals are tested at birth, during childhood and during adulthood, or all individuals have been submitted to and tested after three consecutive drug treatments). Alternatively, run a **Friedman test** if the parametric test cannot be used.

<br/><br/>

***
<!-- UNCOMMENT TO ACTIVATE
Get the Rmarkdown file corresponding to this page on [GitHub](`r GIT`){target="_blank"}.
-->
