```{r}
#| label: setup
#| include: false
library(tidyverse)
source("../Templates/biostats_theme.R")
```

# Introduction

Data analysis are often not done in one step, but there are often several rounds where the data, data analysis and/or figures need to be updated.
If data is added or a mistake has been made, all the scripts have to be run again to update the analysis, figures and output.
This normally takes several rounds and for computational heavy analysis, it can become time consuming.

Targets is a **pipeline tool** for statistics and data science in R.
It takes care of the dependencies of the whole workflow and only updates the steps that are outdated, but skips those where the upstream code has not been changed.
Targets therefore maintains reproducible workflows and avoids unnecessary repetition and can save costly running time.


When is targets useful?

- When the code has a long runtime because it is slow or complex

- When the workflow has interconnected tasks with dependencies

- When there are different outputs (e.g. presentation and report)



::: callout-note
## Reading

Maybe this one:
https://reader.elsevier.com/reader/sd/pii/S2666389920301331?token=018F6FB67370FFD6C7D946BD7ED80F3CEB4522C9D889FAEB0AA631BAF4B2247CA5E6F53497FC629740AABE6349805123&originRegion=eu-west-1&originCreation=20230203150837

Very technical papaer and goes beyond what we do here (git, make, docker and markdown)
Peikert, A., & Brandmaier, A. M. (2021). A Reproducible Data Analysis Workflow. Quantitative and Computational Methods in Behavioral Sciences, 1, Article e3763. https://doi.org/10.5964/qcmb.3763
:::

## Organisation of this book

**First Steps with targets** shows you how to set up a minimal targets plan.

**Towards a Thesis** shows you how to ....

**Fixing Problems** The final section has some trouble shooting suggestions.

::: callout-tip
## targets and drake

Why use targets and what is different from drake?

:::

::: callout-note
## Before you start

You will need to have installed

-   [RStudio](https://www.rstudio.com/products/rstudio/) (version 2022.2 or newer)
-   [R](https://cran.r-project.org/)
-   [quarto](https://quarto.org/docs/get-started/ "Download quarto")
-   quarto R package (`install.packages("quarto")`)
-   targets R package (`install.packages("targets")`)
-   tarchetypes R package (`install.packages("tarchetypes")`)

If you cannot install quarto on your computer (perhaps because of permission problems), either use the [Rmarkdown tutorial](https://biostats-r.github.io/biostats/rmarkdown/index.html), or use [rstudio.cloud](https://rstudio.cloud).
:::
